### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by ZhangHengw** [zhangcaocao/ORBSLAM2_With_YOLOV3#1]
@zhangcaocao ,你好，我在复现时，也是这样的，没有得到论文中的效果，请问下，你知道这是什么原因吗？还有就是你跑自己的数据时 ，是在线跑的，还是采集的数据？

**Comment by zhangcaocao** [comment]
@ZhangHengw  我是自己采集是数据，没有在线跑。论文后面那个分割应该需要调一些参数，然后在实验中使用tum数据集效果贼好，但是使用我自己采集的数据集效果很不好（应该是参数问题，但是我不会调）。所以我就把后面那坨分割直接阉割掉，保留yolov3与orbslam2这个基础，用于后面的扩展。
